In [6]:
import numpy as np
import torch

In [17]:
x = torch.Tensor(3,4)
print("Type:{}".format(x.type()))
print("Size:{}".format(x.size()))
print("Values:\n{}".format(x))

Type:torch.FloatTensor
Size:torch.Size([3, 4])
Values:
tensor([[-3.0689e+31,  4.2249e-41, -3.0689e+31,  4.2249e-41],
        [ 4.4842e-44,  0.0000e+00,  1.5695e-43,  0.0000e+00],
        [ 5.1084e+02,  0.0000e+00,  0.0000e+00,  1.4013e-45]])


In [13]:
x = torch.randn(2, 3)
print(x)

tensor([[ 0.1658,  0.3579,  1.0927],
        [-0.0427,  0.6768, -0.1069]])


In [15]:
x = torch.zeros(2,3)
print(x)
x = torch.ones(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [16]:
x = torch.Tensor([[1,2,3],[4,5,6]])
print("Size:{}".format(x.shape))
print("Values:\n{}".format(x))

Size:torch.Size([2, 3])
Values:
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [18]:
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
x = x.long()
print("Type: {}".format(x.type()))

Type: torch.FloatTensor
Type: torch.LongTensor


In [19]:
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = x + y
print("Size: {}".format(z.shape))
print("Values: \n{}".format(z))

Size: torch.Size([2, 3])
Values: 
tensor([[ 1.1544, -1.1712,  0.9799],
        [-1.0261, -1.3222, -0.1075]])


In [23]:
x = torch.randn(2, 3)
y = torch.randn(3, 2)
z = torch.mm(x, y)
print("Size: {}".format(z.shape))
print("Values: \n{}".format(z))

Size: torch.Size([2, 2])
Values: 
tensor([[1.1340, 5.0419],
        [0.0872, 0.6682]])


In [24]:
x = torch.randn(2, 3)
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))
y = torch.t(x)
print("Size: {}".format(y.shape))
print("Values: \n{}".format(y))

Size: torch.Size([2, 3])
Values: 
tensor([[-0.1723,  1.0582, -1.1429],
        [ 0.0645,  0.4144, -0.1016]])
Size: torch.Size([3, 2])
Values: 
tensor([[-0.1723,  0.0645],
        [ 1.0582,  0.4144],
        [-1.1429, -0.1016]])


In [25]:
z = x.view(3, 2)
print("Size: {}".format(z.shape))
print("Values: \n{}".format(z))

Size: torch.Size([3, 2])
Values: 
tensor([[-0.1723,  1.0582],
        [-1.1429,  0.0645],
        [ 0.4144, -0.1016]])


In [28]:
x = torch.randn(2, 3)
print("Value: \n{}".format(x))
y = torch.sum(x, dim=0)
print("Value: \n{}".format(y))
z = torch.sum(x, dim=1)
print("Value: \n{}".format(z))

Value: 
tensor([[-0.3195, -2.0381,  0.2851],
        [ 0.0365, -0.3264,  1.3785]])
Value: 
tensor([-0.2830, -2.3645,  1.6636])
Value: 
tensor([-2.0725,  1.0885])


In [35]:
x = torch.randn(3, 4)
print("x: \n{}".format(x))
print("x[:1]: \n{}".format(x[:1]))
print("x[:1, 1:3]: \n{}".format(x[:1, 1:3]))

x: 
tensor([[ 0.0796, -0.6100, -0.7012,  0.5655],
        [-1.1403, -1.3795, -0.8577,  0.3892],
        [ 1.5583, -1.0368,  0.2767, -0.6464]])
x[:1]: 
tensor([[ 0.0796, -0.6100, -0.7012,  0.5655]])
x[:1, 1:3]: 
tensor([[-0.6100, -0.7012]])


In [57]:
x = torch.randn(2, 3).to("cuda")
print("Value: \n{}".format(x))
col_indices = torch.LongTensor([0, 2]).to("cuda")
chosen = torch.index_select(x, dim=1, index=col_indices)
print("Value: \n{}".format(chosen))
row_indices = torch.LongTensor([0, 1]).to("cuda")
chosen = x[row_indices, col_indices]
print("Value: \n{}".format(chosen))

Value: 
tensor([[-0.4437,  2.2178, -0.5356],
        [-1.1574, -1.4588,  0.0530]], device='cuda:0')
Value: 
tensor([[-0.4437, -0.5356],
        [-1.1574,  0.0530]], device='cuda:0')
Value: 
tensor([-0.4437,  0.0530], device='cuda:0')


In [51]:
x = torch.randn(2, 3)
print("Value: \n{}".format(x))
y = torch.cat([x, x], dim=0)
print("Value: \n{}".format(y))
z = torch.cat([x, x], dim=1)
print("Value: \n{}".format(z))

Value: 
tensor([[ 0.3338, -0.2902,  0.0858],
        [ 1.3495,  0.3656, -0.3703]])
Value: 
tensor([[ 0.3338, -0.2902,  0.0858],
        [ 1.3495,  0.3656, -0.3703],
        [ 0.3338, -0.2902,  0.0858],
        [ 1.3495,  0.3656, -0.3703]])
Value: 
tensor([[ 0.3338, -0.2902,  0.0858,  0.3338, -0.2902,  0.0858],
        [ 1.3495,  0.3656, -0.3703,  1.3495,  0.3656, -0.3703]])


In [58]:
x = torch.rand(3, 4, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward()
print("Value: \n{}".format(x))
print("x.grad: \n", x.grad)

Value: 
tensor([[0.3828, 0.6155, 0.5390, 0.4034],
        [0.4542, 0.0338, 0.1571, 0.9694],
        [0.7739, 0.0672, 0.7047, 0.1595]], requires_grad=True)
x.grad: 
 tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


In [60]:
x = torch.randn(2, 3)
print("Value: \n{}".format(x))
y = torch.norm(x, dim=-1)
print("Value: \n{}".format(y))

Value: 
tensor([[ 1.6228,  0.2177,  0.0854],
        [ 0.1703, -0.0060,  0.6275]])
Value: 
tensor([1.6396, 0.6502])
